before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq wget
 - mkdir -p /tmp/.cpan/sources/modules
 - (cd /tmp/.cpan/sources/modules && wget http://cpan.cpantesters.org/modules/02packages.details.txt.gz)
 - cpanm --quiet --notest Sereal::Encoder Sereal::Decoder
before_script:
 - (cd cgi-bin && ln -s cpantestersmatrix.yml.travis cpantestersmatrix.yml)
language: perl
perl:
  - "5.18"
  - "5.14"
  - "5.10"
