before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq wget
 - mkdir -p /tmp/.cpan/sources/modules
 - (cd /tmp/.cpan/sources/modules && wget http://cpan.cpantesters.org/modules/02packages.details.txt.gz)
# only needed for plack.t
 - cpanm --quiet --notest Image::Info Plack::Test CGI::Emulate::PSGI CGI::Compile
# optional, by default Storable is used
 - cpanm --quiet --notest Sereal::Encoder Sereal::Decoder
before_script:
 - (cd cgi-bin && ln -s cpantestersmatrix.yml.travis cpantestersmatrix.yml)
# fix shebang for plackup operation
 - (cd cgi-bin && env PERL=$(which perl) perl -pe '$_ = "#!$ENV{PERL} -T\n" if $. == 1' cpantestersmatrix.pl > cpantestersmatrix-travis.pl && chmod 755 cpantestersmatrix-travis.pl)
language: perl
matrix:
  include:
    - perl: "5.20"
# IPv6 address of www.cpan.org is currently slow --- use another mirror instead
    - perl: "5.20"
      env: PERL_CPANM_OPT="--mirror http://cpan.cpantesters.org --mirror https://cpan.metacpan.org"
    - perl: "5.18"
    - perl: "5.14"
    - perl: "5.10"
